# -----------------------------------------------------------------------------
# GLOBAL METADATA
# -----------------------------------------------------------------------------
# THOSE VALUES ARE JUST FALLBACK IF USERS FORGET TO SET THOSE METADATA

# The main title of the document
title: A nice presentation made with present.me

# The description of your presentation (if any)
description: null

# The list of authors for your presentation.
# It can be either a name or a list of names
authors: null

# The date the document has been created/updated
date: null

# The language of the document
# see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang
# Note that if the theme intent to be for right-to-left languages
# you should set the reveal.js rtl option below.
lang: en


# -----------------------------------------------------------------------------
# REVEAL.JS CONFIGURATION
# -----------------------------------------------------------------------------

# reveal.js theme
# see: https://github.com/hakimel/reveal.js#theming
# if set to null, no theme will be applied, you'll have to make your own
# through custom css files in your theme folder.
# see: https://github.com/hakimel/reveal.js/blob/master/css/theme/README.md
theme: simple # black/white/league/beige/sky/night/serif/simple/solarized

# reveal.js syntax highlighting theme
# if set to null, no highlighting theme will be applied, you'll have to make
# your own through custom css files in your theme folder.
# Feel free to pick one at https://github.com/highlightjs/highlight.js/tree/master/src/styles
highlight: monokai # monokai/zenburn

# reveal.js markdown separator rules for markdown files with multiple slides
# inside. Those value will be used to fill the `data-separator`,
# `data-separator-vertical` and `data-separator-notes` attributes.
# see: https://github.com/hakimel/reveal.js#external-markdown
# a falsy value will prevent the attribute to be set, so the default
# reveal.js behavior will be applied.
markdown:
  separator: false # to fill data-separator # default to '^\r?\n---\r?\n$'
  vertical: false # to fill data-separator-vertical # default to no vertical spliting
  notes: false # to fill data-separator-notes # default to '^notes?:'

# reveal.js configuration
# This is our own default overload, for the full list of options and their
# default values, see: https://github.com/hakimel/reveal.js#configuration
options:
  # We default the presentation size to a HD 720p format
  width: 1280
  height: 720

  # We do not display presentation control arrows
  controls: false

  # We do not display the presentation progress bar
  progress: false

  # We display the page number of the current slide
  slideNumber: true

  # Add the current slide number to the URL hash so that reloading the
  # page/copying the URL will return us to the same slide
  hash: true

  # By default we assume the presentation will be in ltr mode
  # Users needing a rtl theme are encourage to create one or
  # to use an existing one
  rtl: false

  # See https://github.com/hakimel/reveal.js/#navigation-mode
  navigationMode: linear # default/linear/grid

  # Global override for preloading lazy-loaded iframes
  preloadIframes: true
